# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20170726_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='file_type',
            field=models.CharField(default='pas', max_length=3),
            preserve_default=False,
        ),
    ]
