# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_picture_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
