# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_picture_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(),
        ),
    ]
