# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20170814_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
